feat(deployement): add a job to verify the program compilation on windows

diff --git a/.github/workflows/deployement.yml b/.github/workflows/deployement.yml
--- a/.github/workflows/deployement.yml
+++ b/.github/workflows/deployement.yml
@@ -44,6 +44,34 @@ jobs:
           fi
           echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT
 
+  check_program_compilation_on_windows:
+    runs-on: windows-latest
+    needs: [check_repository_cleanliness]
+    outputs:
+      summary: ${{ steps.check_if_executable_exists.outputs.summary }}
+      result: ${{ steps.check_if_executable_exists.outputs.result }}
+    steps:
+      - name: Fetch repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - name: Compile project
+        run: |
+          mkdir build
+          cmake -B build
+          cmake --build build --config Release
+      - id: check_binaries
+        name: Check if executable exists
+        run: |
+          echo "summary=| Check if executables exist " >> $GITHUB_OUTPUT
+          if [ -f $CLIENT_BINARY ] && [ -x $CLIENT_BINARY ] && [ -f $SERVER_BINARY ] && [ -x $SERVER_BINARY ] && [ -f $CLIENT_BINARY ] && [ -x $CLIENT_BINARY ]; then
+            echo "result=| :white_check_mark: |" >> $GITHUB_OUTPUT
+          else
+            echo "::error title=Executable not found::The executable $CLIENT_BINARY was not found."
+            echo "result=| :x: |" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+
   check_program_compilation_and_run_tests:
     runs-on: ubuntu-latest
     needs: [check_repository_cleanliness]
